# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftOCTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'AFNetworking'
  # pod 'IAPMessageCenter', '~> 1.0.1.34'

  # Pods for SwiftOCTest

  target 'SwiftOCTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftOCTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
